services:
    market_web:
        container_name: market_web
        image: nginx:alpine
        ports:
            - "8040:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - market_app
        networks:
            - market_network

    market_app:
        container_name: market_app
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        depends_on:
            - market_db
        volumes:
            - ./:/var/www
        networks:
            - market_network
        ports:
            - "9080:9000"

    market_db:
        image: mysql
        container_name: market_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        volumes:
            - market_database:/var/lib/mysql
        networks:
            - market_network  # ❌ Noto‘g‘ri "marker_network" emas, "market_network" bo‘lishi kerak!
        ports:
            -   "3307:3306"
    market_redis:
        container_name: market_redis
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6380:6379"
        networks:
            - market_network

    market_node:
        container_name: market_node
        image: node:alpine
        volumes:
            - ./:/var/www
        command: sh -c "cd /var/www yarn install && run dev"
        depends_on:
            -   market_app
        ports:
            - "8010:8000"

networks:
    market_network:
        driver: bridge

volumes:
    market_database:
